import type {SimulationConfig,DriverManifest,SimulationState,Scalar} from '../types/simulation.js';
import type {CancellationSignal,MaybePromise} from '@interactive-project/protocol/interoperability';
export type RandomSource=()=>number;
export interface StepContext {readonly state:Readonly<Record<string,Scalar>>;readonly parameters:Readonly<Record<string,Scalar>>;readonly inputs:Readonly<Record<string,Scalar>>;readonly dt:number;readonly signal:CancellationSignal;readonly random:RandomSource}
export interface ResetContext {readonly parameters:Readonly<Record<string,Scalar>>;readonly inputs:Readonly<Record<string,Scalar>>;readonly signal:CancellationSignal;readonly random:RandomSource}
export interface DriverHandle {readonly initialState:unknown;step(context:StepContext):MaybePromise<unknown>;reset?(context:ResetContext):MaybePromise<unknown>;dispose():MaybePromise<void>}
export interface Driver {readonly manifest:DriverManifest;initialize(config:SimulationConfig,options:{signal:CancellationSignal;random:RandomSource}):MaybePromise<DriverHandle>}
export interface SimulationTimingOptions {readonly fixedStepSeconds?:number;readonly maxFrameDeltaSeconds?:number;readonly maxCatchUpSteps?:number;readonly stepBudgetMs?:number;readonly seed?:number}
export interface SimulationAdvanceResult {readonly steps:number;readonly pendingSteps:number;readonly alpha:number;readonly droppedTimeSeconds:number;readonly paused:boolean;readonly state:SimulationState}
export interface SimulationSession {readonly manifest:DriverManifest;readonly config:SimulationConfig;getState():SimulationState;input(values:unknown):SimulationState;step(dt:number,options?:{signal?:CancellationSignal}):Promise<SimulationState>;advance(elapsedSeconds:number,options?:{signal?:CancellationSignal}):Promise<SimulationAdvanceResult>;pause():void;resume():void;isPaused():boolean;reset(options?:{signal?:CancellationSignal}):Promise<SimulationState>;dispose():Promise<void>}
export function initializeSimulation(options:{config:unknown;driver:Driver;validateConfig:(input:unknown)=>{valid:boolean};validateManifest:(input:unknown)=>{valid:boolean};policy?:{execution?:boolean;network?:boolean;media?:boolean};signal?:CancellationSignal;timeoutMs?:number;timing?:SimulationTimingOptions}):Promise<SimulationSession>;
