import Ajv2020 from 'ajv/dist/2020.js';
import {readFileSync} from 'node:fs';
import {copySimulation,validFieldValue} from '../index.js';
const ajv=new Ajv2020({strict:true,allErrors:true,ownProperties:true,allowUnionTypes:true}),configSchema=ajv.compile(JSON.parse(readFileSync(new URL('../schemas/simulation.v1.schema.json',import.meta.url)))),manifestSchema=ajv.compile(JSON.parse(readFileSync(new URL('../schemas/driver-manifest.v1.schema.json',import.meta.url))));
const error=(code,path)=>({code,path,severity:'error',message:'The simulation violates its declared contract.'});
export function validateSimulationConfig(input){let config;try{config=copySimulation(input);}catch{return{valid:false,diagnostics:[error('simulation.nonJson','')]};}if(!configSchema(config))return{valid:false,diagnostics:[error('simulation.schema','')]};const diagnostics=[];
 for(const name of ['parameters','inputs','state']){const ids=new Set();config[name].forEach((f,i)=>{const p='/'+name+'/'+i;if(ids.has(f.id))diagnostics.push(error('simulation.duplicateField',p+'/id'));ids.add(f.id);if(!validFieldValue(f,f.default))diagnostics.push(error('simulation.default',p+'/default'));if(f.minimum!==undefined&&f.minimum>f.maximum)diagnostics.push(error('simulation.bounds',p));if(f.unit!==null&&!config.model.units.includes(f.unit))diagnostics.push(error('simulation.unit',p+'/unit'));});}
 for(const key of Object.keys(config.parameterValues)){const field=config.parameters.find(f=>f.id===key);if(!field||!validFieldValue(field,config.parameterValues[key]))diagnostics.push(error('simulation.parameter','/parameterValues/'+key));}
 if(!config.requiredOperations.includes('step'))diagnostics.push(error('simulation.operations','/requiredOperations'));return diagnostics.length?{valid:false,diagnostics}:{valid:true,diagnostics:[]};}
export function validateDriverManifest(input){let m;try{m=copySimulation(input);}catch{return{valid:false,diagnostics:[error('simulation.nonJson','')]};}if(!manifestSchema(m))return{valid:false,diagnostics:[error('simulation.manifest','')]};const keys=new Set(),diagnostics=[];m.models.forEach((v,i)=>{const key=v.id+'@'+v.modelVersion;if(keys.has(key))diagnostics.push(error('simulation.duplicateModel','/models/'+i));keys.add(key);if(!v.dimensions.length)diagnostics.push(error('simulation.dimensions','/models/'+i+'/dimensions'));});if(!m.operations.step)diagnostics.push(error('simulation.operations','/operations/step'));if(m.capabilities.offline&&m.requiredPermissions.includes('network'))diagnostics.push(error('simulation.offline','/requiredPermissions'));return diagnostics.length?{valid:false,diagnostics}:{valid:true,diagnostics:[]};}
